<MainScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10

        ScrollView:
            id: users_scrollview
            GridLayout:
                id: users_list
                cols: 1
                size_hint_y: None
                height: self.minimum_height

        Button:
            id: start_button
            text: 'Start'
            size_hint: 1, None
            height: '48dp'
            on_release: root.controller.start()
